### ISSUE TITLE
The package's API is racy

### ISSUE THREAD

**Issue by nf** [toashd/gopher#2]
The API of the gopher package requires that the user modify fields on a struct while another goroutine reads the fields of that struct. That's a data race, and will lead to undefined and unpredictable behavior in your program. (It's just luck that it works at the moment.)

(Try running your example program with the [race detector](http://blog.golang.org/race-detector) enabled.)

One fix is to provide setter methods that synchronize the accesses to those fields (with a mutex; see the "sync" package).

**Comment by toashd** [comment]
Many thanks for your feedback and pointing out the racy API design and the race detector tool. I've fixed it with a `sync.RWMutex` and setter methods (cf. 28b18e6e5659189268756543282fd6061fb56cbb). Really appreciate your work on golang and its community :+1: .
